"""report_flow — GENERATE Progress_<flow>.md from the ledger + certs + reports.

The protocol's rule (Yoga_orchestration_protocol.md §2.6.4): progress docs are
never hand-written — they are a VIEW over tool-owned state, so they cannot
drift from it. Sources, all read-only:

  skills/graph.yaml            board status per edge/node (single writer = tools)
  <chain_dir>/chain_cert.json  per-seam chained verdicts + wave halt
  <chain_dir>/stage*/route_verdict.json   the routed next rung per failed seam
  <flow_dir>/flow_report.json  the executor's anecdotal pass (done/n_steps)
  skills/decisions.jsonl       audit trail, filtered to this flow's objects

Ends with the exact view command (flow_replay on the stitched states if they
exist, else the executor command that produces them).

Usage (repo root, plain python):
  python tools/report_flow.py --flow data/flows/plank_vinyasa.yaml
Output: <flow_dir>/Progress_<flow>.md
"""
import argparse
import json
import os
import sys
import time

import yaml

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.join(REPO, "tools"))
os.chdir(REPO)
import job_board as jb

PY = "/home/visakii/Documents/moves/env_isaaclab/bin/python"


def load_flow(path):
    flow = yaml.safe_load(open(path))
    name = flow.get("name", os.path.splitext(os.path.basename(path))[0])
    stages = []
    for st in flow["stages"]:
        stype = st.get("type", "edge")
        label = st.get("edge") or st.get("node") or os.path.basename(st["dir"])
        stages.append({"type": stype, "label": label, "dir": st["dir"]})
    return name, stages


def jload(path):
    if path and os.path.exists(path):
        with open(path) as fh:
            return json.load(fh)
    return None


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--flow", required=True, help="flow yaml (executor schema)")
    p.add_argument("--flow_dir", default=None,
                   help="default output/yoga_flows/<name>")
    p.add_argument("--chain_dir", default=None,
                   help="default <flow_dir>/chain_cert")
    p.add_argument("--graph", default=jb.GRAPH_PATH)
    p.add_argument("--ledger", default=jb.LEDGER_PATH)
    p.add_argument("--ledger_n", type=int, default=40)
    p.add_argument("--out", default=None)
    args = p.parse_args()

    name, stages = load_flow(args.flow)
    flow_dir = args.flow_dir or os.path.join("output", "yoga_flows", name)
    chain_dir = args.chain_dir or os.path.join(flow_dir, "chain_cert")
    out = args.out or os.path.join(flow_dir, f"Progress_{name}.md")

    g = jb.load_graph(args.graph)
    chain = jload(os.path.join(chain_dir, "chain_cert.json"))
    execr = jload(os.path.join(flow_dir, "flow_report.json"))
    chain_by = {s["label"]: s for s in (chain or {}).get("stages", [])}
    exec_by = {s["label"]: s for s in (execr or {}).get("stages", [])}

    # objects this flow touches (for the ledger filter)
    objs = set()
    for st in stages:
        if st["type"] == "edge":
            objs.add(f"edge:{st['label']}")
        else:
            objs.add(f"node:{st['label']}")

    L = []
    L.append(f"# Progress — {name}")
    L.append("")
    L.append(f"*GENERATED by `tools/report_flow.py` "
             f"{time.strftime('%Y-%m-%d %H:%M')} — do not hand-edit; "
             "state lives in `skills/graph.yaml` + `skills/decisions.jsonl`.*")
    L.append("")
    if chain:
        verdict = ("**CHAIN CERTIFIED** (pending visual sign-off)"
                   if chain.get("chain_pass") else
                   f"**NOT chain-certified** — first failed seam "
                   f"`{chain.get('first_failed_seam')}`"
                   + (f", wave halted at stage {chain.get('halted_at')}"
                      if chain.get("halted_at") is not None else ""))
    else:
        verdict = "*no chain certification run yet*"
    L.append(f"Chain verdict: {verdict}")
    L.append("")

    # ---- stage table
    L.append("## Stages")
    L.append("")
    L.append("| # | stage | type | board | executor | chain seam | states |")
    L.append("|---|-------|------|-------|----------|------------|--------|")
    open_work = []
    for i, st in enumerate(stages):
        lab = st["label"]
        if st["type"] == "edge":
            e = jb.get_edge(g, lab)
            board = jb.canon(e.get("status", "?")) if e else "NOT ON BOARD"
        else:
            n = jb.get_node(g, lab)
            board = (n or {}).get("status", "NOT ON BOARD")
        ex = exec_by.get(lab) or exec_by.get(lab + "_hold")
        ex_s = f"{ex['done']} @{ex['n_steps']}" if ex else "—"
        ch = chain_by.get(lab)
        if ch:
            seam = ("PASS" if ch.get("seam_pass") else
                    f"FAIL {ch.get('rung') or 'dwell ' + str(ch.get('dwell_pass_rate'))}")
            states = f"{ch.get('n_states_in', '—')}→{ch.get('n_states_out', '—')}"
            if not ch.get("seam_pass"):
                rv = jload(os.path.join(chain_dir, f"stage{ch['i']}_{lab}",
                                        "route_verdict.json"))
                open_work.append((lab, ch, rv))
        else:
            seam, states = "—", "—"
        L.append(f"| {i} | `{lab}` | {st['type']} | {board} | {ex_s} "
                 f"| {seam} | {states} |")
    L.append("")

    # ---- open work: the routed next rung per failed seam (verdicts from tools)
    L.append("## Open work (routed, not improvised)")
    L.append("")
    if not open_work:
        L.append("None — all measured seams pass.")
    for lab, ch, rv in open_work:
        L.append(f"### `{lab}` — {ch.get('rung') or 'node dwell below threshold'}")
        if rv:
            L.append(f"- **rung**: {rv['rung']} → action `{rv['action']}` "
                     f"(target: {rv.get('target')})")
            then = (rv.get("then") or "").strip().replace("\n", " ")
            if then:
                L.append(f"- **instruction**: {then}")
            if rv.get("skipped_attempted"):
                L.append(f"- skipped (already failed): {rv['skipped_attempted']}")
        elif ch.get("dwell_pass_rate") is not None:
            L.append(f"- dwell pass {ch['dwell_pass_rate']} below the chain "
                     "threshold — treat as a seam failure (B1/E1 scheduled step)")
        L.append("")

    # ---- node judge prerequisites surfaced by the board
    needs = []
    for st in stages:
        nid = st["label"] if st["type"] == "node" else st["label"].split("_to_")[-1]
        n = jb.get_node(g, nid)
        if n and (n.get("needs") or n.get("gate_calibrated_on") == "stale"):
            needs.append(f"- `{nid}`: needs {n.get('needs')} "
                         f"(gate_calibrated_on={n.get('gate_calibrated_on')})")
    if needs:
        L.append("## Node judge prerequisites")
        L.append("")
        L.extend(sorted(set(needs)))
        L.append("")

    # ---- ledger excerpt
    L.append("## Audit trail (ledger excerpt)")
    L.append("")
    rows = []
    if os.path.exists(args.ledger):
        with open(args.ledger) as fh:
            for ln in fh:
                r = json.loads(ln)
                if r.get("object") in objs:
                    rows.append(r)
    if rows:
        L.append("```")
        for r in rows[-args.ledger_n:]:
            v = f"  [{r['verdict']}]" if r.get("verdict") else ""
            d = f"  diag={r['diagnosis']}" if r.get("diagnosis") else ""
            L.append(f"{r['ts']} {r['object']}: {r['from']} -> {r['to']} "
                     f"({r['tool']}){v}{d}")
        L.append("```")
    else:
        L.append("*(no ledger entries for this flow's objects yet)*")
    L.append("")

    # ---- the exact view command (always last — the standing rule)
    L.append("## View")
    L.append("")
    states = os.path.join(flow_dir, f"{name}_states.npz")
    L.append("```")
    if os.path.exists(states):
        L.append(f"{PY} mimickit/skillgraph/flow_replay.py --states {states} "
                 "--loops 3")
    else:
        L.append(f"env -u DISPLAY {PY} mimickit/skillgraph/flow_executor.py "
                 f"--flow {args.flow} --out_dir {flow_dir}   # produces "
                 f"{name}_states.npz, then flow_replay.py on a display machine")
    L.append("```")
    L.append("")

    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as fh:
        fh.write("\n".join(L))
    print(f"wrote {out} ({len(L)} lines; {len(open_work)} open seams)")


if __name__ == "__main__":
    main()
